### PR TITLE
Manage the CA list ourselves

### LINKED ISSUE #8: Lib is broken on rebar3 3.14.4
No certificates are loaded (even though compilation succeeds.)

See [certifi PR #44](https://github.com/certifi/erlang-certifi/pull/44).

### LINKED ISSUE #9: Update parse_trans
Some work has been done over `parse_trans` to make it more OTP 24-compatible.

A release request was created: https://github.com/uwiger/parse_trans/issues/47.

- [ ] once that release is created, I'd kindly ask you to import it and create a release for this lib.

Thanks much.

### PR DESCRIPTION
**Pull request by g-andrade**
* Remove dependency on `certifi` - closes #8
* Remove dependency on `parse_trans`'s `ct_expand` transform (explicitly generate the code with hardcoded authorities instead) - closes #9
* Ensure all modules share a single `tls_certificate_check` namespace (rather than `tls_certificate_`.)

cc: @paulo-ferraz-oliveira

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Great work. This effectively removes, in a single pull request, `parse_trans` and `certifi` from all our internal dependencies.

**Comment by paulo-ferraz-oliveira** [comment]
You could suggest getting this into `rebar3`, right (open an Issue, maybe)? The only downside I see is the increase in file size, but that shouldn't be so much of an issue (?). It would, in one go:
* drop `parse_trans` (I'm not sure it's used for anything other than `certifi`),
* solve the "code path" issue introduced by rebar3 3.14.4.

**Comment by g-andrade** [comment]
> You could suggest getting this into rebar3, right (open an Issue, maybe)?

I would be reluctant do it myself, since it could be interpreted as self-serving at best, and hostile at worst (_hey there, drop that lib and use mine instead, eh_.)

But I wouldn't be against others proposing it.

**Comment by paulo-ferraz-oliveira** [comment]
*wink wink* (we'll, I have an open pull request for `certifi` vendoring that I wouldn't mind dropping).

**Pull request merged**
