### PR TITLE
Replace Travis CI with GitHub Actions

### LINKED ISSUE #5: Replace Travis CI with GitHub actions

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Closes #5.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
If you push `ci.yml` to `master` I can rebase and we can see the tests unfold before the merge. It might be safer.

**Review by g-andrade — CHANGES_REQUESTED** [review]
Much obliged.

I kindly ask for analogous changes as requested in [aequitas PR #5](https://github.com/g-andrade/aequitas/pull/5).

(I'm linking to those changes rather than repeating the same comments on the same places and potentially get the same answers a thousand fold, and therefore make myself feel less moronic about the whole thing.)

**Comment by paulo-ferraz-oliveira** [comment]
9e465c4 + 4b40dca

**Comment by g-andrade** [comment]
My gratitude goes out to you, kind sir.

**Comment by g-andrade** [comment]
Ran into a [silly issue](https://github.com/g-andrade/tls_certificate_check/runs/1677374076?check_suite_focus=true), post merge, due to GHA providing an old / buggy version of `rebar3`.

[The fix](https://github.com/g-andrade/tls_certificate_check/commit/d719e6530abab42d480d1be087e6d93a2b4fc5fe) was easy enough.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, I've run into this issue in the past, also. https://github.com/erlang/docker-erlang-otp is the project that keeps the Docker images updated. 19.3, 20.3, 21.3, 22.3, 23.2 should work with latest rebar3, for what it's worth.

**Pull request merged**
